### ISSUE TITLE
固件执行wget不支持https

### ISSUE THREAD

**Issue by jyoryo** [felix-fly/v2ray-padavan-doh#1]
请教下，刷了这个固件发现一个问题，通过命令行执行：wget https://xxx 时显示：
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer

请问是编译包中不支持openssl吗，怎么解决？
谢谢！

**Comment by felix-fly** [comment]
> The wget version included with BusyBox does not support SSL. You can try to use the 'real' wget or curl.

自带的wget不支持的，可以用curl
