### ISSUE TITLE
保存配置文件的时候出错了

### ISSUE THREAD

**Issue by bingyong** [felix-fly/v2ray-padavan-doh#12]
v2022.4.16 的xray版本。
保存配置的时候出现这个报错：
K2P:/home/root # /sbin/mtd_storage.sh save
Save storage files to MTD partition "/dev/mtdblock5"
Error! Invalid storage final data size: 761497

**Comment by felix-fly** [comment]
文件太大超过存储限制。要么减少配置文件体积，要么自己调大存储限制重新编译固件
