### ISSUE TITLE
路由器时间与xray的时间不同步问题

### ISSUE THREAD

**Issue by bingyong** [felix-fly/v2ray-padavan-doh#13]
路由器同步北京时间后，xray打印出来的日志慢8个小时，不知道是不是因为这个问题导致xray无法正常使用。

**Comment by bingyong** [comment]
这个是日志信息：
K2P:/home/root # date
Mon May  2 01:11:40 SST 2022
K2P:/home/root # xray
Xray 1.5.4 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/mipsle)
A unified platform for anti-censorship.
2022/05/01 17:11:45 Using config from STDIN
2022/05/01 17:11:45 [Info] infra/conf/serial: Reading config: stdin:

**Comment by felix-fly** [comment]
跟时区时间没有关系，仔细检查配置

**Comment by bingyong** [comment]
> 跟时区时间没有关系，仔细检查配置

有没有去掉敏感信息后的配置文件哈，我使用你默认的那个不行。

**Comment by felix-fly** [comment]
v2ray的配置本身就很灵活，有各种方式，仓库里只是给出了一种，而且客户端和服务端是相互配合使用的。看日志也不是你这种只输一个xray，要修改配置里的loglevel值，同时要指定配置文件的路径` -config=xxx`
