### ISSUE TITLE
关于硬改内存的K2P A2。

### ISSUE THREAD

**Issue by sunbird84** [felix-fly/v2ray-padavan-doh#14]
你好。我的K2P A2把内存升级到512M，普通的刷机包已经无法使用。同时也硬改了USB接口，需要适配的刷机包。
但是本人只会搞修手机，焊芯片，不会搞软件编译。
想请问你能否在我目前使用的版本上添加XRAY？我想同时拥有SSR和V2RAY这两个梯子。
https://opt.cn2qq.com/padavan/
我用的是https://opt.cn2qq.com/padavan/K2P_DRV_512M_3.4.3.9-099.trx 这个。
作者似乎已经停止开发了，，，所以内核也没有升级了。

**Comment by felix-fly** [comment]
一般情况下编译的固件估计都没有调整storage分区的大小，直接装xray/v2ray无法持久化保存，重启后就没有了。而且16m的存储也不一定都放得下，要你自己编译尝试看看了，按源码里的编译步骤操作 https://github.com/hanwckf/rt-n56u
改存储限制可以参考https://github.com/felix-fly/v2ray-padavan
