### ISSUE TITLE
<建议>hanwckf已经放弃padavan的旧版代码完善了，建议使用keke修改的分支。

### ISSUE THREAD

**Issue by kkjoy** [felix-fly/v2ray-padavan-doh#21]
https://github.com/keke1023/Padavan 集成了kvr，我使用了一段时间感觉挺不错的。当然还可以集成https://github.com/hanwckf/padavan-4.4/commit/ed67df5b8ff58d7cc7deb0dc1a878ef596e4fb17
这个补丁，确实有效果。
相关 https://github.com/hanwckf/rt-n56u/issues/681

**Comment by felix-fly** [comment]
感谢分享，等有空试试。个人目前k2p当主路由不开无线，相当的稳。

**Comment by kkjoy** [comment]
close
