### ISSUE TITLE
可以集成xray吗

### ISSUE THREAD

**Issue by yywii** [felix-fly/v2ray-padavan-doh#3]
xray性能更好

**Comment by felix-fly** [comment]
新的release下加上了

**Comment by MuenYu** [comment]
@felix-fly 请问可以直接删除低版本的xray，然后自己更换高版本的替换进去吗？

**Comment by felix-fly** [comment]
不知道你具体的需求，所有的都是开源可见，自己修改就好

**Comment by MuenYu** [comment]
> 不知道你具体的需求，所有的都是开源可见，自己修改就好

我的需求是：在不更新固件的情况下更新 xray 版本，做法就是直接替换二进制，请问可行吗？

**Comment by felix-fly** [comment]
系统是只读的，固件内置的文件不能删除，可以不打包进固件，也可以在用户空间或者内存安装需要的文件
