### ISSUE TITLE
配合smartdns删除v2ray .ips文件后iptables出错

### ISSUE THREAD

**Issue by yywii** [felix-fly/v2ray-padavan-doh#4]
/etc/storage/xray/iptables.sh: line 3: can't open /etc/storage/v2ray/ad.ips: no such file
/etc/storage/xray/iptables.sh: line 4: can't open /etc/storage/v2ray/gw.ips: no such file
iptables v1.4.16.3: Set ad doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.16.3: Set gw doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
是不是不用删除ips文件

**Comment by felix-fly** [comment]
用xray的话，需要把两个脚本文件 check.sh iptables.sh 里的v2ray 都替换成xray

**Comment by kkjoy** [comment]
我保留了ips 删除了host 正常了
