### ISSUE TITLE
大侠如有可能能不能编译一个HC5661A的，不盛感激

### ISSUE THREAD

**Issue by thofd** [felix-fly/v2ray-padavan-doh#5]
大侠如有可能能不能编译一个HC5661A的，不盛感激

**Comment by felix-fly** [comment]
我看你不是fork了吗，没有编译成功吗？ @thofd

**Comment by thofd** [comment]
是啊，我编译完了菜单里没有xray选项

**Comment by felix-fly** [comment]
没有界面的，通过ssh配置

**Comment by jx3118** [comment]
我硬改了32+512能出个自己用的吗？

**Comment by felix-fly** [comment]
> 我硬改了32+512能出个自己用的吗？

你是指HC5661A设备？可以用github自己编译啊，就改改配置文件

**Comment by jx3118** [comment]
> > 我硬改了32+512能出个自己用的吗？
> 
> 你是指HC5661A设备？可以用github自己编译啊，就改改配置文件

是K2P硬改的。

**Comment by felix-fly** [comment]
厉害了  个人一直用原始的，感觉基本够用了啊
没弄过硬改的，目测应该是和下面的配置项有关，你可以试试看
https://github.com/hanwckf/rt-n56u/blob/master/trunk/configs/boards/K2P/kernel-3.4.x-5.0.config
`CONFIG_RT2880_FLASH_32M`
`CONFIG_RT2880_DRAM_512M`

**Comment by jx3118** [comment]
小白不会自己加插件，只能用人家模板自动编译。

**Comment by felix-fly** [comment]
@jx3118 编译了一下，你试试看
https://github.com/felix-fly/v2ray-padavan-doh/actions/runs/1268821438

**Comment by jx3118** [comment]
@felix-fly 万分感谢，等回家后测试。

**Comment by jx3118** [comment]
> 没有界面的，通过ssh配置

我硬改的也没配置界面吗？硬改过就是想开机能用。

**Comment by felix-fly** [comment]
界面和硬改没关系的，界面需要额外的开发才能实现的
ssh配置也只需要配一次，后续重启 重刷都没影响
