### ISSUE TITLE
请教一个问题：IP是如何传递ipset 的gw集

### ISSUE THREAD

**Issue by yywii** [felix-fly/v2ray-padavan-doh#64]
iptable创建了gw集，但是没看到ip add gw集，是smartdns解析域名后会把ip归到gw集吗？但我看conf没看到相关ipset规则，所以很奇怪ip是如何传递ipset 的gw集，请大佬赐教。

**Comment by felix-fly** [comment]
smartdns 通过 ipset 设置的，在 [gw.hosts](https://github.com/felix-fly/v2ray-padavan-doh/blob/master/smartdns/gw.hosts) 文件里

**Comment by yywii** [comment]
> smartdns 通过 ipset 设置的，在 [gw.hosts](https://github.com/felix-fly/v2ray-padavan-doh/blob/master/smartdns/gw.hosts) 文件里

拉到下面看到了ipset，感谢大佬的解答
