### ISSUE TITLE
关于smartdns配置的一点建议

### ISSUE THREAD

**Issue by yywii** [felix-fly/v2ray-padavan-doh#65]
现在大佬这个方案非常舒服，xray能跑满宽带，关键不会卡死k2p，但大佬的gw.hosts配置既要nameserver 又要ipset，查阅smartdns官方资料，https://pymumu.github.io/smartdns/config/forwarding-with-ipset/
添加如下配置，gw.hosts只需配置域名就可以
domain-set -name gw -file /etc/storage/smartdns/gw.hosts
domain-rules /domain-set:gw/ -ipset gw -c none -address #6 -nameserver gw

如果smartdns更新到41，可以添加如下配置
#测速失败后，自动添加到IPSet
ipset-no-speed gw
这样就不用担心gw.hosts覆盖不全

**Comment by felix-fly** [comment]
你提供的方法很好，大大减少了规则文件的体积，配置也更灵活
