### ISSUE TITLE
v2的配置文件格式是不是有问题来着，没有path了

### ISSUE THREAD

**Issue by bingyong** [felix-fly/v2ray-padavan-doh#8]

**Comment by felix-fly** [comment]
非常感谢你的细心发现。xray没独立的时候有xtls，后来没了就去掉改成tcp了，实际中一般不会用这个，现在换回原始的ws了，配置这一块还是要根据个人需求来，这里只是个样例仅供参考

**Comment by bingyong** [comment]
主要是得考虑到大部分的小白用户哈，对于技术宅来说，一个配置文件可能几分钟的事情，对于小白来说，只会按配置文件文件要求来填入信息，少了一些参数之后，肯定就会出现各种个样的bug。
