### ISSUE TITLE
如何自定义要走代理的网站域名

### ISSUE THREAD

**Issue by mailfarmer** [felix-fly/v2ray-padavan-doh#9]
大神，我用smartdns模式，有些国外网站想走代理，怎么自己添加？

**Comment by felix-fly** [comment]
修改gw.hosts文件，添加nameserver和ipset规则

**Comment by mailfarmer** [comment]
添加完了，如何让它即时生效呢？

**Comment by felix-fly** [comment]
kill掉smartdns进程 手动再启动或者等2分钟cron执行自动启动
